# Generated by Django 6.0.1 on 2026-01-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('salary_period', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('qualifications', models.TextField()),
                ('benefits', models.JSONField()),
                ('openings', models.IntegerField()),
                ('deadline', models.DateField()),
                ('hiring_priority', models.CharField(max_length=100)),
                ('requirements', models.JSONField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
    ]
