# Generated by Django 6.0.1 on 2026-01-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='headline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='portfolio',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='resume/')),
                ('portfolio', models.FileField(null=True, upload_to='portfolio/')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('relocation', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('culture', models.CharField(max_length=100, null=True)),
                ('non_negotiable', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('preferred', models.CharField(max_length=100, null=True)),
                ('salary_expectation_minimum', models.IntegerField(null=True)),
                ('salary_expectation_maximum', models.IntegerField(null=True)),
                ('currency', models.CharField(max_length=100, null=True)),
                ('goals', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.JSONField(null=True)),
                ('soft_skills', models.JSONField(null=True)),
                ('certifications', models.CharField(max_length=100, null=True)),
                ('languages', models.JSONField(null=True)),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
