# Generated by Django 6.0.1 on 2026-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_register_headline_register_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='jobTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
