# Generated by Django 6.0.1 on 2026-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_education_degree_education_end_year_education_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='currently_working',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
