# Generated by Django 6.0.1 on 2026-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='currently_working',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
