# Generated by Django 6.0.1 on 2026-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_education_currently_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='skills',
            field=models.JSONField(null=True),
        ),
    ]
