# Generated by Django 6.0.1 on 2026-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_education_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
