# Generated by Django 6.0.1 on 2026-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_preference_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
