# Generated by Django 6.0.1 on 2026-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
