# Generated by Django 6.0.1 on 2026-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='Submitted', max_length=100),
        ),
    ]
