from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.index),
    path('register/', views.register),
    path('company-register/', views.company_register),
    path('login/', views.login),
    path('user/', views.user),
    path('adminp/', views.admin),
    path('company/', views.company),
    path('new-companies/', views.new_companies),
    path('manage-company/<id>/<status>/', views.manage_company),
    path('companies/', views.companies),
    path('add-job/', views.add_job),
    path('jobs/', views.jobs),
    path('edit-job/<id>/', views.edit_job),
    path('delete-job/<id>/', views.delete_job),
    path('profile/', views.profile),
    path('professional-details/', views.professional_details),
    path('experience-details/', views.experience_details),
    path('experience-continue/', views.experience_continue),
    path('education-details/', views.education_details),
    path('education-continue/', views.education_continue),
    path('skills-details/', views.skills_details),
    path('preference-details/', views.preference_details),
    path('file-details/', views.file_details),
    path('job-lists/', views.job_lists),
    path('job-details/<id>/', views.job_details),
    path('applications/', views.applications),
    path('manage-applications/', views.manage_applications),
    path('update-status/<id>/<status>/', views.update_status),
    path('email/', views.email),
    path('otp/', views.otp),
    path('password/', views.password),
    path('company-profile/', views.company_profile),
    path('users/', views.users),
    path('manage-user/<id>/<status>/', views.manage_user),
]